import { Inter } from "next/font/google";
import "../globals.css";
import { Toaster } from "react-hot-toast";
import Provider from "@components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Auth of Chatify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/assets/logo.svg" type="image/x-icon" />
      <body className={`${inter.className} bg-[#f2f2f2]`}>
        <Provider>
          <Toaster />
          {children}
        </Provider>
      </body>
    </html>
  );
}
